# Generated by Django 2.2.19 on 2021-02-23 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Grocery',
        ),
    ]
